// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkyilebhirvpuzsrtjuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRreWlsZWJoaXJ2cHV6c3J0anVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTE0NzgsImV4cCI6MjA2MzgyNzQ3OH0.CpNEc653Pkzt2ITgNz6H81OrGUY1WrH0XiGiR_h8DgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);